setwd("~/R/proj/nohrsc")
library(sf)
library(rgdal)
library(tidyverse)

spdf_entbasins <- readOGR("basins.kml", "cnrfc_09122018_basins_thin")
spdf_basinzones <- readOGR(".","cnrfc_zones_wgs84aux")

#pnts1 <- readOGR("riverFcast.kml", "![CDATA[River Guidance <br><a href="http://www.cnrfc.noaa.gov/rfc_guidance.php">CNRFC River Forecast Web Page</a>]]")

# Convert spatialpolydf to an sf object
sf_entbasins <- spdf_entbasins %>%  st_as_sf()  %>% 
  mutate(Description = as.character(Description), 
         rivgroupkml = gsub(".*<tr> <td>Group</td> <td>(.+)</td> </tr> <tr bgcolor=\"#D4E4F3.*", "\\1", Description ),
         desckml = gsub(".*Basin</td> <td>(.+)</td> </tr> </table> </td> </tr> </table> </body> </html>", "\\1", Description ),
         nwscodekml = Name) %>% select(-Description, -Name) %>%
  
  # https://stackoverflow.com/questions/39086400/extracting-a-string-between-other-two-strings-in-r
  
  
  
  
  # Join the data
  left_join(df, by = c("nwscodekml" = "nwscode")) %>% mutate(location = trimws(location))
# get area 
#  mutate(area_m = st_area(geometry), area_a = as.numeric(area_m*0.000247105), area_mi = round(area_a/640, 0),
#       swe_ft = round(swe_kaf*1000 / area_a , 2))  %>%
#  mutate(swe_ft = ifelse(swe_ft == Inf, 0, swe_ft))
#sf_5nona <- sf_5 #%>% na.omit()

sf_basinzones <- spdf_basinzones %>% st_as_sf() %>%  #%>% transmute(Name, geometry)  %>%
# Join the data
#left_join(df, by = c("Name")) %>%
# get area 
 mutate(area_m = st_area(geometry), area_a = as.numeric(area_m*0.000247105), area_mi = round(area_a/640,2))
    #   swe_ft = round(swe_kaf*1000 / area_a , 2)) %>% 
 #mutate(swe_ft = ifelse(swe_ft == Inf, 0, swe_ft))  %>% filter(!zone == "total")

areatest <- sf_basinzones %>% filter(Name == "PLLC1HUF" | Name ==  "IIFC1HLF" | Name ==  "SCBC1HUF")

rivgroups <- unique(sf_entbasins$rivgroupkml)
rivgroups
df_t <- sf_entbasins %>% 
  
  
  filter(
    param == "swe") %>% mutate(value = as.character(value), value = as.double(value),
                               nwscodekml = as.factor(nwscodekml)) %>%
  filter(location == "Entire Basin")  %>% 
  #filter(nwscodekml == "FRAC1") %>%
  mutate(desckml = as.factor(desckml)) %>%
  filter(rivgroupkml != "SouthernCalifornia") %>% 
  filter(rivgroupkml != "UpperSacramento") %>%    
  filter(rivgroupkml != "LowerSacramento") %>% 
  filter(rivgroupkml != "RussianNapa") %>% 
  filter(rivgroupkml != "CentralCoast") %>% 
  filter(rivgroupkml != "NorthCoast") %>% 
  filter(rivgroupkml != "N_SanJoaquin") %>% 
  filter(rivgroupkml != "CachePutah") %>%  
  filter(rivgroupkml != "Humboldt") %>% 
  filter(rivgroupkml != "Klamath") #%>% 

#filter(date > ymd("2019-04-01")) %>%  #for testing format
#ungroup() #%>%
#na.omit() 
#%>% filter(value > 0) good for spatial, not sliding bars

#date <- df_t$date
#value <- df_t$value
#desckml <- df_t$desckml
#rivgroupkml <- df_t$rivgroupkml
#df_tx <- data.frame(date, value, desckml, rivgroupkml)

#ggplot(df_t, aes(date, value)) + geom_line() #+ facet_wrap(~rivgroupkml)  


#p <- ggplot(df_t) + geom_sf(aes(fill = value)) + transition_manual(date) + labs(title = "date: {current_frame}") +
#    scale_fill_viridis_c() + theme_dark()
#p
#ggplot(df_t, aes(date, value)) + geom_point() + facet_wrap(~nwscodekml)
#########################################
############# moving bars ###############
#########################################
df_t <- df_t %>%
  group_by(date) %>%
  # The * 1 makes it possible to have non-integer ranks while sliding
  mutate(rank = min_rank(-value) * 1,
         Value_rel = value/value[rank==1],
         Value_lbl = paste0(" ",value)) %>%
  filter(rank <=35) %>%
  ungroup()

p <- ggplot(df_t, aes(rank, group = desckml, 
                      fill = as.factor(rivgroupkml), color = as.factor(rivgroupkml))) +
  geom_tile(aes(y = value/2,
                height = value,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(desckml, " ")), vjust = 0.2, hjust = 1, color = "black") +
  geom_text(aes(y=value,label = paste0(Value_lbl,"   ",rivgroupkml), hjust=0), color = "black") +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  theme_dark() +
  labs(title='{closest_state}', x = "", y = "Basin Average Snow Water Equivalent [inches]",
       caption = "Data Source: NOAA | Plot generated by Derek Lister @Lister") +
  theme(plot.title = element_text(hjust = 0, size = 22),
        axis.ticks.y = element_blank(),  # These relate to the axes post-flip
        axis.text.y  = element_blank(),  # These relate to the axes post-flip
        plot.margin = margin(1,4,1,7, "cm")) +
  theme(legend.position="bottom", legend.direction="horizontal") +
  
  transition_states(date, transition_length = 4, state_length = 1) #+
#ease_aes('cubic-in-out')

animate(p, 200, fps = 10, duration = 40, width = 800, height = 600, renderer = gifski_renderer("gganim_bars.gif"))

################ 
#########transition reveal 
############
df_t <- unique(df_t)
df_t <- df_t %>% arrange(date)
p <- ggplot(df_t, aes(date, value, group = desckml, color = rivgroupkml)) + 
  geom_line() + 
  geom_segment(aes(xend = max(df_t$date)+1, yend = value), linetype = 2, colour = 'grey') + 
  geom_point(aes(color = rivgroupkml), size = 2) + 
  geom_text(aes(x = max(df_t$date)+1 ,color = rivgroupkml, label = paste0(desckml, " (", nwscodekml,")")), hjust = 0) + #paste0(desckml, " (", nwscodekml, ")")), hjust = 0) + 
  #geom_label_repel(aes(y = value, max(df_t$date), label = desckml), hjust = 1, nudge_x = 20) +
  transition_reveal( date) + 
  coord_cartesian(clip = 'off') + 
  theme_black(base_size = 22) +
  labs(title = 'NOAA NOHRSC output, Water Year 2019', y = 'Snow Water Equiv [inches]', x = element_blank(),
       caption = "Data Sources: NOAA CNRFC / NOAA NOHRSC | Plot: D.O'Connor")  + 
  # theme(legend.position = "bottom") +
  scale_x_date(breaks = "1 month", date_labels = "%b") +
  #scale_color_viridis_d() + 
  scale_colour_brewer(type = "qual") +
  
  theme(legend.position="bottom", legend.direction="horizontal") +
  theme(plot.margin = margin(5.5, 240, 5.5, 15)) +
  theme(legend.title=element_blank()) + 
  theme(legend.text=element_text(size=14)) + 
  #theme(legend.background = element_rect(fill="lightblue",
  #                                         size=0.5, linetype="solid", 
  #                                        colour ="darkblue")) +
  guides(color = guide_legend(override.aes = list(size=2, stroke=1.5))) +
  scale_y_continuous(sec.axis = dup_axis(name = NULL)) + 
  theme(text = element_text(size=18))
animate(p, fps = 10, duration = 35, end_pause = 150,width = 1000, height = 840, renderer = gifski_renderer("gganim_lines.gif"))
gganimate(p, "output_test.mp4")


ptest <- ggplot(df_t, aes(date, value, group = desckml, color = rivgroupkml)) + 
  geom_line() + 
  # geom_segment(aes(xend = max(df_t$date)+1, yend = value), linetype = 2, colour = 'grey') + 
  # geom_point(aes(color = rivgroupkml), size = 2) + 
  #geom_text(aes(x = max(df_t$date)+1 ,color = rivgroupkml, label = paste0(desckml, " (", nwscodekml,")")), hjust = 0) + #paste0(desckml, " (", nwscodekml, ")")), hjust = 0) + 
  #geom_label_repel(aes(y = value, max(df_t$date), label = desckml), hjust = 1, nudge_x = 20) +
  #transition_reveal( date) + 
  # coord_cartesian(clip = 'off') + 
  labs(title = 'CNRFC Sierra Basins w/NOHRSC output, Water Year 2018', y = 'Snow Water Equiv [inches]', x = element_blank(),
       caption = "Data Sources: NOAA CNRFC / NOAA NOHRSC | Plot: D.O'Connor")  + 
  # theme(legend.position = "bottom") +
  
  scale_x_date(breaks = "1 month", date_labels = "%b") +
  #scale_color_viridis_d() + 
  scale_colour_brewer(type = "qual") +
  theme_black(base_size = 22) +
  theme(legend.position="bottom", legend.direction="horizontal") +
  theme(plot.margin = margin(5.5, 240, 5.5, 15)) +
  theme(legend.title=element_blank()) + 
  theme(legend.text=element_text(size=14)) + 
  # theme(legend.background = element_rect(fill="lightblue",
  #                                       size=0.5, linetype="solid", 
  #                                      colour ="gray")) +
  guides(color = guide_legend(override.aes = list(size=2, stroke=1.5))) +
  scale_y_continuous(sec.axis = dup_axis(name = NULL)) + 
  theme(text = element_text(size=18))
ptest





df_t <- data.frame(date, value, desckml, rivgroupkml)